version: '2.1'

services:

  git-server:
    #image: jkarlos/git-server-docker
    build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
      - /srv/git/keys:/git/keys
      - /srv/git/repos:/repos
