version: '2-wych'

services:

  git-server:
    image: jkarlos/git-server-docker
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - /srv/git/keys:/git-server/keys
    - /srv/git/repos:/git-server/repos

